### ISSUE TITLE
[log included] No renewal, how to interpret logs?

### ISSUE THREAD

**Issue by jazari-akuna** [fatk/docker-letsencrypt-nginx-proxy-companion-examples#19]
Hi,
I have no auto renewal and am not sure how to interpret the logs :
````
Unhandled error has happened, traceback is above

Debugging tips: -v improves output verbosity. Help is available under --help.
Creating/renewal chat.aausat.com certificates... (chat.aausat.com)
2017-02-15 10:19:18,579:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1401, in main
    return main_with_exceptions(cli_args)
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1386, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1282, in persist_new_data
    client = registered_client(args, existing_data.account_key)
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1224, in registered_client
    client = acme_client.Client(directory=args.server, key=key, net=net)
  File "build/bdist.linux-x86_64/egg/acme/client.py", line 63, in __init__
    self.net.get(directory).json())
  File "build/bdist.linux-x86_64/egg/acme/messages.py", line 169, in from_json
    raise jose.DeserializationError(str(error))
DeserializationError: Deserialization error: Wrong directory fields

Unhandled error has happened, traceback is above

Debugging tips: -v improves output verbosity. Help is available under --help.
Sleep for 3600s
````
(This keeps repeating)

My certs directory are correctly configured.
If you know what's going on...

Thanks in advance for your time.

**Comment by fatk** [comment]
It's a [known issue](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/161) and it has been fixed, you should update `jrcs/letsencrypt-nginx-proxy-companion` to 1.4+

**Comment by jazari-akuna** [comment]
OK I just needed to remove the container and re-run it to finish the
upgrade, thanks!
